### ISSUE TITLE
OD Explorer showing main star with a ring planet icon

### ISSUE THREAD

**Issue by Ash-Raimon** [WarmedxMints/OD-Explorer#1]
OD EXPLORER Version 0.9.4

This update brings in so much more customizable UI, and its awesome. I especially love the distance calculation!

**The Issue:**
 I've been testing it for a short time, and so far I've seen the UI keeps showing me the main star "A" always has the "Rings" icon.
![Star001](https://user-images.githubusercontent.com/44728397/146649983-3e5edc85-bbe5-46d3-ae5c-9536cc97fe82.jpg)
![Star00](https://user-images.githubusercontent.com/44728397/146649719-0549cb04-1a17-4186-821b-e78d74678d2b.jpg)

**Feature Request:**
I see you have added icons to customize the UI under display settings, and that's brilliant. If it's also possible to add an icon (or a blue color on top of an existing body icon) showing which bodies are landable. This would also help out if these high gravity/atmospheric pressure planets are landable or not for odyssey. I would suggest the color to be on top of the planet's icon under the Name tab, or where ever you see fit.
Thank you!

**Comment by WarmedxMints** [comment]
The rings icon shows because the star has an asteroid belt around it.  If you look in the system map, you should see a belt between the star and its first body.  The icon shows when the scan of the body reports more than zero rings.  I could just disable it on stars.

As for a landable icon, I did;t bother with one as the surface gravity, pressure and temp only display if the body is landable.  So if you see surface gravity, then it is landable.

**Comment by Ash-Raimon** [comment]
Regarding the landable planets, I haven't thought about the gravity/atm/temp would only show on landable ones, that make sense. Thanks for clarifying, come to think of it, with the gravity icon, now it makes landable planets clearer.

For the main star having ring planet icon with asteroid belt, it did kinda confuses me a little, especially when its shown in between the planet list, or at the lowest one, which kinda blends itself with other planets. Perhaps its me not yet used to the new UI.

But what happens if there is a second star in the system with another asteroid belt near it? I assume it would also have a ring planet icon?

Because no matter what type of descending order I put it in, it will always be listed either at the end of the planet list, or at the lower descending order. An example of that would be having a mapped value descending order, it would show the main star with a mapped value of 109,095 Cr and listed at the end with a ring icon.
![image](https://user-images.githubusercontent.com/44728397/146654177-d03f5b97-97b5-4686-960d-01a46f373d47.png)

In any case, I'd say this is a resolved issue albeit minor UI behavior that I can get used to.

**Comment by WarmedxMints** [comment]
I'll change it to ignore rings on stars.  

As for the sorting, currently, the system first sorts by stars, putting them to the bottom of the list, then it sorts by Vauleable bodies reported by EDSM, putting them at the top and then finally by whatever your settings are.  I'll add an option to include stars in your sorting.

**Comment by Ash-Raimon** [comment]
Thank you
