### ISSUE TITLE
Export to CSV error

### ISSUE THREAD

**Issue by Remanent** [WarmedxMints/OD-Explorer#10]
In the window for Biological data, when you click export to CSV, it prompts you for a save location and filename, and once filled out, and you click save, i receive this prompt:

![image](https://user-images.githubusercontent.com/1380222/232078110-4382bb70-d318-42bc-9bb6-891eb8cf25f8.png)

**Comment by WarmedxMints** [comment]
I think I've found the reason for this and it is hopefully fixed in v10.6

https://github.com/WarmedxMints/OD-Explorer/releases/tag/v1.0.6
