### ISSUE TITLE
Rocky Bodies have value up to 200.000, which is incorrect

### ISSUE THREAD

**Issue by rinart73** [WarmedxMints/OD-Explorer#12]
This rocky body is non-terraformable, yet it has a max value of 190.000.

![image](https://github.com/WarmedxMints/OD-Explorer/assets/1765611/efd0314d-71a5-40fb-8127-614b48a84ee7)

Data in EDSM is correct: https://www.edsm.net/en/system/bodies/id/83563152/name/NGC+2546+Sector+ZK-N+d7-63/details/idB/473490054/nameB/NGC+2546+Sector+ZK-N+d7-63+7+d

**Comment by WarmedxMints** [comment]
Can you post the journal entry for the scan please?

**Comment by WarmedxMints** [comment]
I think I found the issue and it should be fixed in v1.0.9
