### ISSUE TITLE
Valuable Body Notifications

### ISSUE THREAD

**Issue by WiseNat** [WarmedxMints/OD-Explorer#13]
Currently valuable bodies in known systems exist within the app:
![image](https://github.com/WarmedxMints/OD-Explorer/assets/56839545/8e269ef2-bf51-4ded-ade8-47c995e75426)

It'd be nice if there were an option to allow notifications for these when you pop into their system.

**Comment by WarmedxMints** [comment]
This has been added in versions 2
https://github.com/WarmedxMints/OD-Explorer/releases/tag/v2.0.0
