### ISSUE TITLE
Worth Mapping Overlay

### ISSUE THREAD

**Issue by WiseNat** [WarmedxMints/OD-Explorer#14]
Currently the notifications are incredibly useful but when you're FSS-ing a whole system you'll typically you'll have to go back into the main OD Explorer application to see which valuable bodies are recommended to be mapped.

It'd be nice if there were an option to have a 'Worth Mapping' overlay panel somewhere ingame.

## Component
![Topbar](https://github.com/WarmedxMints/OD-Explorer/assets/56839545/6374d8ea-ebb9-48ca-b406-b6a1c2ac251a)

## In-game Mockup
![Mock](https://github.com/WarmedxMints/OD-Explorer/assets/56839545/a31e7fd2-3973-4e7a-a143-1e8f300c4127)

Due to screen space limitations, the proposal would only show the nearest valuable body to the player. This shouldn't impose any issues when it comes to systems with large numbers of valuable bodies.

Once the body in the component has been scanned, the next closest body will be displayed. If valuable bodies are scanned out of order then the "Bodies Remaining" segment would be the only part that'd need updating.

**Comment by WarmedxMints** [comment]
This has been added in version 2
https://github.com/WarmedxMints/OD-Explorer/releases/tag/v2.0.0
