### ISSUE TITLE
Select All can't Deselect All

### ISSUE THREAD

**Issue by AlexMarvik** [WarmedxMints/OD-Explorer#15]
Hi !

In Display Options, under Notable Body Options, I can Select / Deselect All under Planet Class, but I can not Deselect All under Atmosphere Class and Volcanism. This isn't very practical when I need to select a few Atmospheres, for example.

Thank you very much for this tool, it's very effective and pleasing to the eye. One of my favorite tools.

**Comment by WarmedxMints** [comment]
This should be fixed in v1.0.8
