### ISSUE TITLE
Version 1.0.10 will not install

### ISSUE THREAD

**Issue by poeticbulldozer** [WarmedxMints/OD-Explorer#16]
I've just downloaded the latest version of OD Explorer (the full application, not the portable one) and the installer flat out refuses to open in Windows 10. I get a vague statement saying "this app can't run on your PC" and no other information. The previous version, 1.0.9.0, installs and runs just fine - was there a change in requirements for running the app between versions, or is this an issue on your end?
![Screenshot 2024-06-26 160929](https://github.com/WarmedxMints/OD-Explorer/assets/29004691/f9ad8927-bab0-4db1-b7ec-82f89236361b)

**Comment by WarmedxMints** [comment]
It looks like an issue on your end as the file size is zero. 

Version 2 is out now, hopefully that will be fine.
https://github.com/WarmedxMints/OD-Explorer/releases/tag/v2.0.0
