### ISSUE TITLE
od explorer forgets notification position

### ISSUE THREAD

**Issue by internethering** [WarmedxMints/OD-Explorer#17]
hey, thanks for your great tool. but one problem: when I switch notification position to top right, it forgets at the next start and post notifications top right. I'm using last version of od explorer

**Comment by WarmedxMints** [comment]
Hopefully, this is sorted in version 2.   It should be as it saves where the notifications are set.

https://github.com/WarmedxMints/OD-Explorer/releases/tag/v2.0.0
