### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by tdimaggio** [WarmedxMints/OD-Explorer#2]
Hey WarmedxMints,

Sorry if this isn't the appropriate channel, but do you have a donations button?  I'd like to buy you a brew or a coffee for all the amazing work on OD Explorer.   I started a second account just dedicated to exploration and out of all the tools I've messed around with for exploration, OD Explorer just rules!

Thanks!
Tony (CMDR Homel4nder)

**Comment by WarmedxMints** [comment]
Yes, there is one in the about window which you can find in the options menu.

Thanks as well, I am glad you like it and find it helpful.
