### ISSUE TITLE
Geological / biological icons not shown

### ISSUE THREAD

**Issue by BCLV4** [WarmedxMints/OD-Explorer#4]
Hello, new user of OD-E, I can't show the geological nor biological icons in the main window. I tried every options, but it doesn't work.

I'm on Windows 10, with all latest versions of drivers, and .Net v5

My settings : 
[https://cdn.discordapp.com/attachments/969522988661764148/1041600376597643374/image.png](url)

And the results :

[https://cdn.discordapp.com/attachments/974218752478576651/1041557898788098068/image.png](url)

[https://cdn.discordapp.com/attachments/974218752478576651/1041557899136213022/image.png](url)

**Comment by BCLV4** [comment]
After several tests, it seems OD-E is not compatible when the game is not in english langage. When I switch the game in english, I can see the geologocal / biological icons.

**Comment by WarmedxMints** [comment]
I shall take a look and see what I can do.  I'll try my best although my French teacher at school was terrible! :D

**Comment by WarmedxMints** [comment]
This should now be fixed (I hope) in v1.0.1.  Please let me know if that isn't the case.  Thanks, o7

https://github.com/WarmedxMints/OD-Explorer/releases/tag/v1.0.1

**Comment by BCLV4** [comment]
Sorry, I was not in exploration on the last days. I will check it this week end.

**Comment by BCLV4** [comment]
I've just tested the 1.0.1 version, with my game in French.

It works properly, biological icons are shown correctly !

Many thanks !

**Comment by BCLV4** [comment]
Just a last point on this issue, is it normal to have the exobiological icon disappearing when planet is mapped ?

<img width="355" alt="image" src="https://user-images.githubusercontent.com/11680379/206417162-99ed9718-04f1-491d-a640-62ba401b8700.png">
