### ISSUE TITLE
Exobiological specie not listed in the DB

### ISSUE THREAD

**Issue by BCLV4** [WarmedxMints/OD-Explorer#5]
I found a system with 6 exobiologicals genus

One of the genus specie is not listed in OD-E when I scan it (Tussock (Touradon in french) Divisa yellow)

Is it a bug or just the genus / specie is not listed in the OD-E DB ?

The system :
<img width="400" alt="image" src="https://user-images.githubusercontent.com/11680379/206409192-49da8abc-7b79-41cf-9e29-aa251ed4affb.png">

The scan :
<img width="539" alt="image" src="https://user-images.githubusercontent.com/11680379/206409239-d49ffd9c-62bc-4f88-abf2-8f14d9b02e0f.png">

The result in OD-E (Biological data panel) :
<img width="490" alt="image" src="https://user-images.githubusercontent.com/11680379/206409455-dff05a1c-8fd8-450d-9d54-1027489129c1.png">

**Comment by WarmedxMints** [comment]
The system doesn't work that way.  It lists whatever the journal reports and then looks up the values and scan range in a dictionary.  So it could be some journal events were missed/not fired or it didn't know what planet you were on for some reason.  That could happen if you logged out or closed the app between scans on the same body.

**Comment by BCLV4** [comment]
I didn't close the app during all my whole session. So, if I well understand, it's a bug in logs from Elite event recorder for this specific specie.
