### ISSUE TITLE
Need information about privacy

### ISSUE THREAD

**Issue by 68498468** [WarmedxMints/OD-Explorer#6]
Hello,

OD explorer needs an internet connection to work.
What data is being sent? and where?
An offline mode would be possible even if it is less accurate?

**Comment by WarmedxMints** [comment]
Only thing being sent is the system ids for the route and current system.  This is just to pull the system value and valuable bodies info from EDSM.

Mainly to get a json, for example - https://www.edsm.net/api-system-v1/estimated-value?systemName=Sol
