### ISSUE TITLE
OD Explorer crashing with Tussock Ignis

### ISSUE THREAD

**Issue by killyox** [WarmedxMints/OD-Explorer#7]
Hi, since OD Explorer 1.0.3 (or patch 14), my OD Explorer crashes when I scan a Tussock Ignis.
I play with French language.
Could you please help me ? 
Thanks

**Comment by WarmedxMints** [comment]
I can't think why that would happen, can you provide some logs from the journal files of the scans which caused it please?

**Comment by WarmedxMints** [comment]
This should be fixed in the latest release.
